name: Build Application
on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]    # ubuntu-latest, macos-latest,
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run make
#    - name: Upload Artifacts
#      uses: actions/upload-artifact@v3
#      with:
#        name: installer-${{ matrix.os }}
#        path: |
#          out/make/**/*.exe
#          out/make/**/*.dmg
#          out/make/**/*.deb
#          out/make/**/*.AppImage
    - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')  # This ensures the release step only runs for tag events.
        with:
          files: |
            out/make/**/*.exe
            out/make/**/*.dmg
            out/make/**/*.deb
            out/make/**/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
